### ISSUE TITLE
[Feature]: MDX basic typography and layout styles

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/blog#699]
## Custom MDX Components

- [x] [Ant Design typography](https://ant.design/components/typography-cn/)

[Components List](https://mdxjs.com/table-of-components/):

- [x] a
- [x] br
- [x] hr
- [x] h1
- [x] h2
- [x] h3
- [x] h4
- [x] h5
- [x] h6
- [x] p
- [x] img
- [x] li
- [x] ol
- [x] ul
- [x] pre
- [x] code
- [x] strong
- [x] em
- [x] del
- [x] blockquote
- [x] section
- [x] aside
- [x] sup
- [x] table
- [x] tbody
- [x] td
- [x] th
- [x] thead
- [x] tr
- [x] input

```css
/* thanks for 'https://github.com/sindresorhus/github-markdown-css' */
@media screen and (prefers-reduced-motion: reduce) {
  .markdown-body a::before {
    position: absolute;
    bottom: 0;
    left: 50%;
    width: 0;
    height: 2px;
    content: '';
    background-color: #1890ff; /* primary for color palette */
    transition: none;
  }
}

.markdown-body a::before {
  position: absolute;
  bottom: 0;
  left: 50%;
  width: 0;
  height: 2px;
  content: '';
  background-color: #1890ff; /* primary for color palette */
  transition: all 0.2s ease-in-out;
}

.markdown-body a:active,
.markdown-body a:hover,
.markdown-body a:focus {
  outline-width: 0;
}

.markdown-body a:active::before,
.markdown-body a:hover::before,
.markdown-body a:focus::before {
  left: 0;
  width: 100%;
}

.markdown-body a:not([href]) {
  color: inherit;
  text-decoration: none;
}

.markdown-body h1::before,
.markdown-body h2::before,
.markdown-body h3::before,
.markdown-body h4::before,
.markdown-body h5::before,
.markdown-body h6::before {
  position: absolute;
  top: -2px;
  left: -1.3em;
  font-weight: 800;
  color: inherit;
  content: '#';
  opacity: 0;
  transform: scale(0);
}

@media screen and (prefers-reduced-motion: no-preference) {
  .markdown-body h1::before,
  .markdown-body h2::before,
  .markdown-body h3::before,
  .markdown-body h4::before,
  .markdown-body h5::before,
  .markdown-body h6::before {
    transition: transform 0.2s ease-in-out, opacity 0.2s ease-in-out;
  }
}

.markdown-body h1:hover::before,
.markdown-body h2:hover::before,
.markdown-body h3:hover::before,
.markdown-body h4:hover::before,
.markdown-body h5:hover::before,
.markdown-body h6:hover::before,
.markdown-body h1:focus::before,
.markdown-body h2:focus::before,
.markdown-body h3:focus::before,
.markdown-body h4:focus::before,
.markdown-body h5:focus::before,
.markdown-body h6:focus::before {
  opacity: 1;
  transform: scale(1);
}

/* remove anchor added by gatsby-autolink-headers */
.markdown-body h1 svg,
.markdown-body h2 svg,
.markdown-body h3 svg,
.markdown-body h4 svg,
.markdown-body h5 svg,
.markdown-body h6 svg {
  display: none;
}

.markdown-body h2::after {
  position: relative;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  flex-grow: 1;
  width: auto;
  height: 3px;
  margin: 1em 2px 0 3px;
  content: '';
  background: linear-gradient(
    to right,
    #1890ff,
    #40a9ff
  ); /* primary to secondary */

  border-radius: 2px;
}

.markdown-body h2 {
  color: #1890ff; /* primary for color palette */
}

.markdown-body h3 {
  color: #f76707; /* orange for color palette */
}

.markdown-body h4 {
  color: #7048e8; /* violet for color palette */
}
```

## Enhanced Typography and A11Y

- [x] [External link `a` component](https://github.com/rehypejs/rehype-external-links/blob/main/index.js)
- [x] [Autolink heading](https://github.com/rehypejs/rehype-autolink-headings)
- [x] A11y `input` checkbox component.
